name: Docker Image CI

on:
  workflow_dispatch:

jobs:
 
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . -t devdevil1/devdevil
    - name: login
      run: docker login -u devdevil1 -p darkdevil9234? && docker push devdevil1/devdevil
